// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadNortwindOrders.Models.Models;

public partial class ServedCustomer
{
    public int EmployeeId { get; set; }

    public string EmployeeName { get; set; }

    public int? TotalCustomersServed { get; set; }
}